- package-lock.json
- package.json
- src/from-car.ts
Updates exporter to a new branch with a commit that adds the dist folder to have the types (the dist folder is created in the release). There were type failures before, but it was due to the exporter to depend on the importer old version, which had the old CID. So, I linked also there the new one.
This also removed the `CarReaderish` type definition in favour of simply accepting `CarReader|CarIndexedReader` in `fromCar`
> fix: use exporter with types

- src/blockstore/fs.ts
- test/blockstore/index.node.test.ts
Several put operations in fsBlockstore could lead to try to open multiple times. 
Closes #15
> fix: fs blockstore race condition

- README.md
- src/cli/cli.ts
- src/pack/fs.ts
- show the .car extention in the output
- line up the output
- add a note to the README about curling CARs from the gateway
```console
ipfs-car --pack ~/Downloads/GMT20210520-203336_Recording_1920x1576.mp4
root CID: bafybeiefsr3v4tbbudkwr6uooeld2bp4cbkpsbgyiyqj6uiu3j2pau4ogy
output: GMT20210520-203336_Recording_1920x1576.car
```
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
> fix: show the full filename in output for --pack

- package.json
Trying this out in nft.storage Node.js example was also problematic. This is because Node thinks the esm folder is cjs. The two solutions were to rename the files to `*.mjs` or add a package.json with that. How typescript build does not handle this is strange, but their compile should not be thought for multiple compiles and not using the original `package.json`
> fix: add package json to esm build to hint module

- package-lock.json
- package.json
- src/blockstore/fs.ts
- src/blockstore/memory.ts
- src/pack/blob.ts
- src/pack/fs.ts
- src/pack/index.ts
- src/pack/stream.ts
- src/unpack/fs.ts
- tsconfig.json
Because [nodejs requires file extensions for relative imports](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions), the current esm build fails to use in Node.js
As an example, importing `packToBlob`:
```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/vsantos/work/pl/gh/protocol/nft.storage/packages/client/examples/node.js/node_modules/ipfs-car/dist/esm/pack/' is not supported resolving ES modules imported from /Users/vsantos/work/pl/gh/protocol/nft.storage/packages/client/examples/node.js/node_modules/ipfs-car/dist/esm/pack/blob.js
```
This PR uses [ttsc](https://github.com/cevek/ttypescript) to rely on a custom transformer, which during the build adds the `.js` extension to relative imports. Note that `index.js` is not inferred and `index` needed to be added …
> fix: esm imports need js extension

- package-lock.json
- src/pack/blob.ts
- src/pack/index.ts
- src/unpack/index.ts
This PR exports external types so that consumers do not have to import modules like unixfs to access them
Package lock was also updated
> chore: export external types

- src/unpack/index.ts
When trying to use `unpack` with esm we get the following error
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/oli/Code/filecoin-storage/filecoin.storage/packages/client/node_modules/uint8arrays/equals' imported from /Users/oli/Code/filecoin-storage/filecoin.storage/packages/client/node_modules/ipfs-car/dist/esm/unpack/index.js
Did you mean to import uint8arrays/equals.js?
The generated code previously was
```js
import equals from 'uint8arrays/equals';
```
and now is
```js
import { equals } from 'uint8arrays';
```
This is likely related to `uint8arrays/equals` exporting default and/or `uint8arrays` do not have exports property in [package.json](https://github.com/achingbrain/uint8arrays/blob/master/package.json).
> fix: do not use uint8array default export

- package-lock.json
- package.json
- src/blockstore/idb.ts
- src/blockstore/index.ts
- test/blockstore/index.browser.test.ts
- test/blockstore/index.node.test.ts
- add IdbBlockStore impl on top of idb-keyval
- add browser only test for IdbBlockStore and MemoryBlockStore
- updates BlockStore interface so that get(cid) can return undefined if the the block is not in the store
License: (Apache-2.0 AND MIT)
Signed-off-by: Oli Evans <oli@tableflip.io>
> feat: idb blockstore

- README.md
- package.json
- src/blockstore/README.md
- src/unpack/fs.ts
- src/unpack/index.ts
- test/unpack/index.browser.test.ts
- test/unpack/index.node.test.ts
Takes an AsyncIterable and yields UnixFSEntries.
```js
import fs from 'fs'
import { unpackStream } from 'ipfs-car/unpack'
const inStream = fs.createReadStream(`${process.cwd()}/output.car`)
const files = []
for await (const file of unpackStream(inStream)) {
// Iterate over files
}
```
License: (Apache-2.0 AND MIT)
Signed-off-by: Oli Evans <oli@tableflip.io>
> feat: add unpackStream

- src/blockstore/fs.ts
- test/blockstore/index.node.test.ts
When destroying fsblockstore before it is open (tmp folder created), it errors to remove a not existent folder.
> fix: fs blockstore destroy without open

- package-lock.json
- package.json
- src/blockstore/fs.ts
- src/blockstore/memory.ts
This PR updated the interface types and also updated the dependencies
Not sure what changed, as this was working yesterday, but probably a mismatch of CID versions causing this.:
```
npm ERR! src/lib.js(107,9): error TS2322: Type 'MemoryBlockStore' is not assignable to type 'Blockstore'.
npm ERR!   Types of property 'put' are incompatible.
npm ERR!     Type '({ cid, bytes }: { cid: CID; bytes: Uint8Array; }) => Promise<{ cid: CID; bytes: Uint8Array; }>' is not assignable to type '(block: Block) => Promise<Block>'.
npm ERR!       Types of parameters '__0' and 'block' are incompatible.
npm ERR!         Type 'Block' is not assignable to type '{ cid: CID; bytes: Uint8Array; }'.
npm ERR!           Types of property 'cid' are incompatible.
npm ERR!             Type …
```
> fix: memory blockstore types

- src/pack/index.ts
- src/pack/stream.ts
- test/pack/index.node.test.ts
Fixes bug introduced by `wrapWithDirectory` (context: https://github.com/ipfs/js-ipfs-unixfs/issues/159)
Also adds `wrapWithDirectory` in `packToStream` which I previously missed 🤦🏼‍♂️
> fix: empty input array

- src/pack/index.ts
Ref: https://github.com/web3-storage/ipfs-car/pull/73 /cc @jimpick
Bear with me ... This is because of the challenges of using asynciterables as streams, but we can do this!
In the current form, the promises for `writer.put()` and `writer.close()` get lost, so (a) we have no means of backpressure so if we had a fast block store + a large number of blocks and a slow reader for the output then we'd use up a lot of memory, and (b) any errors are lost to the wind.
The CAR internals for `{writer,out}` ("IteratorChannel") are careful to [maintain backpressure](https://github.com/ipld/js-car/blob/master/lib/iterator-channel.js) between them if you choose to use `await` on your `writer.put()` (because it's not strictly necessary), so the approach in this PR _should_ maintain a steady stream state …
> fix: async CAR put() & close() for backpressure & error handling

- src/cli/cli.ts
It seems that there is some controversy on this subject (#57, #88, #89) -- I'm not sure on the finer points discussed, but in practice I need to emit a root CID without wrapping to match how my other DAGs are processed in estuary. The files come from a system that does not rely on fs level metadata (Internet Archive, file metadata is stored separately in an xml system) so I don't need the wrapper. I think threading this through gives users the flexibility to get the behavior they need.
```
$ ./dist/cjs/cli/cli.js --pack ../derive-car/test/item/ --output /tmp/item.car
root CID: bafybeidmfmezmxnhnx4pnolbqriolgivs3xqcecsw7lbaiytjwqb4hidr4
output: /tmp/item.car
$ ipfs-car --list /tmp/item.car 
bafybeidmfmezmxnhnx4pnolbqriolgivs3xqcecsw7lbaiytjwqb4hidr4 …
```
> Give CLI users the option to wrap or NOT wrap with directory

- package-lock.json
- package.json
This updates `multiformats` to `^9.6.3` and `@ipld/car` to `^3.2.3` (both the current latest versions).
This seems to fix the error I'm seeing in metaplex when importing the `nft.storage` client:
```
yarn run v1.22.17
$ tsc -p ./src
../../node_modules/ipfs-car/dist/types/blockstore/memory.d.ts:7:5 - error TS2416: Property 'blocks' in type 'MemoryBlockStore' is not assignable to the same property in base type 'Blockstore'.
Type '() => AsyncGenerator<{ cid: CID; bytes: Uint8Array; }, void, unknown>' is not assignable to type '() => AsyncGenerator<Block, void, unknown>'.
Call signature return types 'AsyncGenerator<{ cid: CID; bytes: Uint8Array; }, void, unknown>' and 'AsyncGenerator<Block, void, unknown>' are incompatible.
The types returned by 'next(...)' are incompatible between these …
```
> chore: update @ipld/car and multiformats deps

- test/pack/index.node.test.ts
- test/unpack/index.node.test.ts
Tests are flaky by removing tmp files from disk. This only happens in some windows machines in github actions that likely do not have permissions in the tmp folder. This can just be ignored and move forward as this does not represent any problem with the actual code.
Closes #106
> test: make rm temporary files tolerant to errors in windows

- README.md
This just adds a note about the `--wrapWithDirectory` flag to the README to close #113
> chore: add --wrapWithDirectory cli flag to README

- src/pack/blob.ts
- test/pack/index.browser.test.ts
We now have an official IANA media type for CARs `application/vnd.ipld.car` so use it here.
see: https://github.com/web3-storage/web3.storage/issues/1206
see: https://www.iana.org/assignments/media-types/application/vnd.ipld.car
License: (Apache-2.0 AND MIT)
Signed-off-by: Oli Evans <oli@tableflip.io>
> feat!: iana media type application/vnd.ipld.car

- .gitignore
- README.md
- src/cli/cli.ts
- src/cli/lib.ts
- src/cli/verbose-handler.ts
- src/pack/fs.ts
- src/pack/index.ts
- src/pack/stream.ts
In order for people to have a much easier time with associating CIDs with the filename, there is now the option `--list-full` that displays on the same line the CID and the file path.
A verbose option is available with the packing function.
It allows to print which file is being processed during packing.
> Display cids with associated filename

- README.md
We can now use Gateways for this, no need for exposing internal Kubo RPC. 
Ref.  
- https://github.com/ipfs/go-ipfs/pull/8758
- https://docs.ipfs.tech/reference/http/gateway/#api
- https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#format-request-query-parameter
@vasco-santos mind merging and releasing as a patch, so docs at https://www.npmjs.com/package/ipfs-car are updated? :pray:
> docs: use gateway CAR responses

- bin.js
- cmd/blocks.js
Checks the block hash consistency when listing blocks in the CAR. Pass `--no-verify` to disable.
e.g.
```console
$ ipfs-car blocks ciqaih44edpp6equhdeacnifzxpqfoyr425e3hjef2autya5ohuq5ty.car
bafk2bzaceb6ddglkmua3upv2hhapl5dhklkc27xggtmndq6nqmtfkoay54gbs
bafk2bzacedu4gpmt2aqhq5gznjdmz4anxf64l34heez67rllizb6izvuqzava
file:///Users/alan/Code/web3-storage/ipfs-car/node_modules/@web3-storage/car-block-validator/esm/src/index.js:52
throw new Error('CID hash does not match bytes');
^
Error: CID hash does not match bytes
at validateBlock (file:///Users/alan/Code/web3-storage/ipfs-car/node_modules/@web3-storage/car-block-validator/esm/src/index.js:52:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Module.blocksList …
```
> feat(cli): check block hash consistency when listing blocks

- bin.js
- cmd/hash.js
- test/bin.node.test.js
Pass `-m` or `--only-multihash` to instruct `ipfs-car hash` to output a base58btc encoded multihash instead of a CID.
e.g.
```console
$ ipfs-car hash ./test/fixtures/comic.car --only-multihash
zQmbJeNsbY4jTphnsZ4RBHG2jC8STcBanGVPi3V3A9FQxSU
```
> feat(cli): hash can output a base58btc encoded multihash
